import { starterTemplate, type LandingPageConfig } from '@/src/templates/landing-page/starter'

function titleCase(value: string) {
  return value
    .split(/\s+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ')
}

export function buildLandingPageConfig(input: {
  offerSummary: string
  targetAudience: string
  primaryGoal: string
  company?: string | null
  packageLabel?: string | null
  revisionNote?: string | null
}): LandingPageConfig {
  const headline = input.offerSummary.trim().replace(/\.$/, '')
  const audience = input.targetAudience.trim().replace(/\.$/, '')
  const goal = input.primaryGoal.trim().replace(/\.$/, '')
  const revisionNote = input.revisionNote?.trim()

  return {
    ...starterTemplate,
    eyebrow: input.company ? `${input.company} launch` : starterTemplate.eyebrow,
    headline: titleCase(headline),
    subheadline: `Built for ${audience}. Primary action: ${goal}.`,
    cta: goal,
    sections: [
      {
        title: 'Offer',
        body: `${headline}. This page is written to make the value proposition obvious in the first screen.`,
      },
      {
        title: 'Audience',
        body: `The page speaks directly to ${audience} with a single clear promise and a low-friction path to act.`,
      },
      {
        title: 'OperatorOS delivery plan',
        body: `Package: ${input.packageLabel ?? 'custom'}. CTA goal: ${goal}.${revisionNote ? ` Latest revision request: ${revisionNote}.` : ''}`,
      },
    ],
  }
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

export function renderLandingPageHtml(config: LandingPageConfig) {
  const sections = config.sections
    .map(
      (section) => `
        <section class="card">
          <h2>${escapeHtml(section.title)}</h2>
          <p>${escapeHtml(section.body)}</p>
        </section>
      `,
    )
    .join('')

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>${escapeHtml(config.headline)} — OperatorOS Draft</title>
    <style>
      :root { color-scheme: dark; }
      body { margin: 0; font-family: Inter, Arial, sans-serif; background: #09090b; color: #f4f4f5; }
      .wrap { max-width: 980px; margin: 0 auto; padding: 48px 20px 80px; }
      .eyebrow { color: #67e8f9; text-transform: uppercase; letter-spacing: 0.2em; font-size: 12px; }
      h1 { font-size: clamp(42px, 8vw, 72px); line-height: 1.02; margin: 16px 0; }
      .sub { max-width: 760px; color: #d4d4d8; font-size: 20px; line-height: 1.5; }
      .cta { display: inline-block; margin-top: 28px; padding: 14px 22px; border-radius: 999px; background: #67e8f9; color: #111827; font-weight: 700; text-decoration: none; }
      .grid { display: grid; gap: 18px; margin-top: 46px; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); }
      .card { background: rgba(24, 24, 27, 0.92); border: 1px solid rgba(63, 63, 70, 0.95); border-radius: 20px; padding: 22px; }
      .card h2 { margin: 0 0 10px; font-size: 20px; }
      .card p { margin: 0; color: #d4d4d8; line-height: 1.6; }
      .footer { margin-top: 52px; color: #a1a1aa; font-size: 14px; }
    </style>
  </head>
  <body>
    <main class="wrap">
      <div class="eyebrow">${escapeHtml(config.eyebrow)}</div>
      <h1>${escapeHtml(config.headline)}</h1>
      <p class="sub">${escapeHtml(config.subheadline)}</p>
      <a class="cta" href="#contact">${escapeHtml(config.cta)}</a>
      <div class="grid">${sections}</div>
      <p class="footer" id="contact">Draft generated by OperatorOS Studio.</p>
    </main>
  </body>
</html>`
}
